# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: af36cd286f37c35e8729fb3a75a68a6f67c1e5ac24ad1ec809357ee9fd53dab4db4f890998f3664b045d4eb80ae32fad0f6787a142b765c120963ac9869ce99c

test:
  secret_key_base: 6676549a9748172b016c82ffc46fe609679ba2ea4f1d44f289d0903e1b984be1664e2c8dab1a0366f842f7779711c45cb4fc94d16e8b0b22d27b5b5eef41cc1e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
